version: '3.5'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - '.:/usr/src/web'
      - 'app_dependencies:/usr/src/web/node_modules'
    env_file:
      - '.env'
volumes:
    app_dependencies:
